### ISSUE TITLE
[PE-D][Tester A] Add command - input validation for number of calories

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T17-2/tp#110]
![image.png](https://raw.githubusercontent.com/Ssatu/ped/main/files/5c1ea5aa-cdef-4b18-b823-186eb7bb949c.png)

Hi, I managed to add an item that seems implausible to be true.

![image.png](https://raw.githubusercontent.com/Ssatu/ped/main/files/63a6fbff-9f41-4581-b5d2-0249bb5e6c50.png)

Upon further testing, I notice that there indeed exists some input validation for calories of items that are "too large". However, the upper limit is not specified and it seems to have been set at too high of a value. Perhaps we could lower it to something that would accurately identify user input errors (based on the fact that meals of such a high calorie count do not exist)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: Ssatu/ped#1

**Comment by nicolelim02** [comment]
Won't fix

**Comment by nicolelim02** [comment]
Won't fix.
