### ISSUE TITLE
[PE-D][Tester C] setup feature is throwing inaccurate exception for when ideal weight is too small.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T17-2/tp#118]
![image.png](https://raw.githubusercontent.com/jwdavis0200/ped/main/files/4fa2d9a0-cb93-4046-ae10-18491ac9d1b9.png)

The ideal weight here is 0.9 which is a very small non-integer, exception thrown however is as shown above which is not accurate to the user.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: jwdavis0200/ped#4

**Comment by xav168** [comment]
updated UG to clarify what can be keyed into the setup command
